# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

PeerOrgs:
  # ---------------------------------------------------------------------------
  # Hospital B
  # ---------------------------------------------------------------------------
  - Name: HospitalB
    Domain: hospB.example.com
    EnableNodeOUs: true
    Template:
      Count: 3
      SANS:
        - localhost
    Users:
      Count: 1
